### ISSUE TITLE
Parse error for indented string inside a list

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nix-idea#13]
The plugin shows a parse error on ``[ ''a'' ]``, which should be valid.

![screenshot from 2017-12-18 12-52-40](https://user-images.githubusercontent.com/399718/34120086-73662b0e-e3f2-11e7-84bf-d7b6fa880f19.png)

**Comment by JojOatXGME** [comment]
Thanks for the report. I'm currently rewriting the parser. I will check your case against the new implementation.
