### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by jnoortheen** [NixOS/nix-idea#14]
Seems like this plugin not compatible with latest intellij editors. Is this project still maintained?

**Comment by jonringer** [comment]
last commit was almost 3 years, so I would lean towards no.

**Comment by jonringer** [comment]
However, it might not be much work to create compatible plugins for later idea versions.

**Comment by Tristan971** [comment]
Indeed it was quite easy, see #15. Hopefully this gets merged in, but in the meantime it's there.

**Comment by Mic92** [comment]
A new version was just released: https://github.com/NixOS/nix-idea/releases/tag/v0.3.0.3

**Comment by Mic92** [comment]
We have now full automated github releases thanks to @JojOatXGME
