### ISSUE TITLE
Improve test coverage (and rewrite parser)

### ISSUE THREAD

**Issue by JojOatXGME** [NixOS/nix-idea#24]
The project currently lacks automatic tests for the Java implementation. Within this ticket, I want to add tests for the most important components.

**Comment by JojOatXGME** [comment]
While working on this ticket, I noticed some issues with the parser. I initially wanted to fix the issues incrementally, but I eventually decided to rewrite the parser. I guess I might create a pull request at the end of the week.

Anyway, I noticed that the parser of the plugin had support for some expressions and keywords I couldn't find in the *Nix* language itself. The related keywords are

 *  `require`,
 *  `requires`,
 *  `import`, and
 *  `imports`.

@pSub or @Mic92, do you have any idea where these keywords are coming from? Did *Nix* had any breaking changes which might have removed these keywords?

@edwtjo, I mention you because you have created the initial version of the parser five years ago according to *GitHub*. The initial version already supported these keywords. Maybe you can still remember the background?

**Comment by Mic92** [comment]
Imports is used only in NixOS modules where it is not a module but an attribute in your configuration attribute set. `import` is a builtin function as you found out. I have never saw `require` or `requires` being used for anything.

**Comment by JojOatXGME** [comment]
Just a short update for everyone interested:

My new parser implementation seems to work fine as long as the file is valid. I currently try to find a good approach to recover from syntax errors. I actually created [a post on *intellij-support.jetbrains.com* about one of my problems](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010379000-Grammar-Kir-Synchronize-state-between-lexer-and-parser). I will invest some more time and try to find a good solution. Anyway, I hope that even without reliable error recovery, my new parser implementation (with test coverage and Nix 2.3-support) would be an improvement.

My current status can be found on [the `tests` branch of my fork](https://github.com/NixOS/nix-idea/compare/master...JojOatXGME:tests). However, if you look at this branch, be aware that I rebase this branch from time to time.
