### ISSUE TITLE
Add color settings

### ISSUE THREAD

**Issue by GauthierPLM** [NixOS/nix-idea#3]
It would be nice to have some settings to choose colors. Currently, most of the code use the default color, but I would like to colorize it a bit more (purple for keys, yellow for function names, ...).

**Comment by JojOatXGME** [comment]
I added a page for color settings in #54. I will therefore close this ticket. If you have specific wishes for changes regarding these settings, you can either create a new issue, or add a comment and I will reopen this issue.
