### ISSUE TITLE
New automatic checks for pull requests

### ISSUE THREAD

**Issue by JojOatXGME** [NixOS/nix-idea#33]
[Since travis-ci.org is ceased](https://blog.travis-ci.com/2021-05-07-orgshutdown), there are no-longer any automatic builds verifying the pull requests of this repository. While it is possible to migrate to travis-ci.com, I have no idea who would be responsible for that. Since we are already using GitHub Actions for our release process, I think I would just set up a workflow with GitHub Actions.

@Mic92 Do you have any objections? Do you know whether there are any guidelines regarding the use of GitHub Actions within the NixOS “organization” on GitHub? I could not find anything about that. I am just wondering because GitHub might eventually charge the organization for the usage if it is not using the free plan. ([About billing for GitHub Actions](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions))

**Comment by Mic92** [comment]
No objections, we don't have any limitation as a github org since all repos are public.

**Comment by JojOatXGME** [comment]
@Mic92 You are right, I should have read the first paragraph. 😅

> GitHub Actions usage is free for both public repositories and self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage, depending on the product used with the account.

**Comment by Mic92** [comment]
This can be closed, I think.
