### ISSUE TITLE
Add support for PhpStorm

### ISSUE THREAD

**Issue by ricardoboss** [NixOS/nix-idea#35]
Hi! I'd like to request support for PhpStorm. Would that be possible? I've seen you also support WebStorm and I'm not sure if there is a big difference, really.

**Comment by ricardoboss** [comment]
nvm

**Comment by ricardoboss** [comment]
What I meant was support for the latest Intellij version, but I'm sure you're already aware of that.

**Comment by JojOatXGME** [comment]
Thanks anyway. I guess we should improve the update process so that we support the new version (based on the release candidate) before it is released by JetBrains. Unfortunately, I am too busy right now. Anyway, you can track #36 regarding the update for IDEA 2021.3.
