### ISSUE TITLE
Support New Features of the Nix Expression Language

### ISSUE THREAD

**Issue by JojOatXGME** [NixOS/nix-idea#39]
The parser was updated to Nix 2.3 in pull request #27. There were a few updates since then:

#### [Nix 2.4](https://nixos.org/manual/nix/stable/release-notes/rl-2.4.html)

* Antiquotations in paths, e.g. `./${foo}` instead of `./. + foo`.

#### [Nix 2.5](https://nixos.org/manual/nix/stable/release-notes/rl-2.5.html)

* Lists can now be compared lexicographically using the `<` operator.

#### [Nix 2.6](https://nixos.org/manual/nix/stable/release-notes/rl-2.6.html)

* *No changes of the language*

#### [Nix 2.7](https://nixos.org/manual/nix/stable/release-notes/rl-2.7.html)

* *No changes of the language*

I couldn't find any language change in the changelog (besides new built-ins) up to version 2.13.

**Comment by kubijo** [comment]
Any change of this moving forward?

**Comment by JojOatXGME** [comment]
There is pull request #60 by @jansorg, which is about the string interpolations (formerly antiquotations) in paths.
