### ISSUE TITLE
<list expr> or NixTokenType.] expected

### ISSUE THREAD

**Issue by hectorj** [NixOS/nix-idea#4]
Hi!

I have this line in a set: `networking.firewall.allowedTCPPorts = [ 8080 ];` and it's being highlighted as this syntax error: `<list expr> or NixTokenType.] expected, got '8080'`.

But `nix-ops` consumes the file without any issue, which makes me say it is valid syntax.

Plugin version: 0.2.0.1
IDE: Goglang 1.0 EAP

**Comment by pSub** [comment]
I have some syntax fixes in the pipeline. I will check if they fix your problem too and try to prepare a PR.
