### ISSUE TITLE
trailing comma in function argument list is incorrectly reported as an error

### ISSUE THREAD

**Issue by hab25** [NixOS/nix-idea#46]
```
❯ cat test.nix
{
  # the plugin reports the error " 'foo' unexpected ", unless we remove the comma
  foo,
}:
foo
```
But Nix can understand the file just fine:
```
nix-repl> import ./test.nix { foo = 2; }
2
```
---
#### Environment:
Nix IDEA Version 0.4.0.4
Intellij IDEA Ultimate version 2022.1.3 (build 221.5921.22)
```
❯ nix --version
nix (Nix) 2.9.1
```

**Comment by JojOatXGME** [comment]
Thanks for the report. I somehow thought that trailing commas would be illegal in the Nix Expression Language. I checked the history of the parser definition, but it looks like trailing commas were possible, even back in 2014.

https://github.com/NixOS/nix/blob/cd49fe4f9b338242e1e404fd4dbb0a3ebc1c3a12/src/libexpr/parser.y#L519-L528

I will try to fix this in the next week. Just in case someone else is interested in trying to fix this issue: The relevant part of the source code is here.

https://github.com/NixOS/nix-idea/blob/452fe69174874fb7f9c17bdc6b4f608d809a324d/src/main/lang/Nix.bnf#L99

A test case could be added here.

https://github.com/NixOS/nix-idea/blob/452fe69174874fb7f9c17bdc6b4f608d809a324d/src/test/testData/ParsingTest/Function.nix#L1-L9
https://github.com/NixOS/nix-idea/blob/452fe69174874fb7f9c17bdc6b4f608d809a324d/src/test/java/org/nixos/idea/lang/ParsingTest.java#L26-L28

**Comment by hab25** [comment]
Thanks @JojOatXGME! 
By the way, I only found this error because the trailing comma was inserted by the excellent nix formatter https://github.com/kamadorueda/alejandra.
How it compares to popular alternatives: https://github.com/kamadorueda/alejandra#alternatives
