### ISSUE TITLE
Division with antiquotation not parsed properly

### ISSUE THREAD

**Issue by jansorg** [NixOS/nix-idea#59]
I noticed this while adding support for antiquotations in paths (https://github.com/NixOS/nix-idea/issues/39).

https://nixos.org/manual/nix/stable/language/values.html:
> a.${foo}/b.${bar} is a syntactically valid division operation.

But `/.` of the expression above is currently parsed as PATH.

**Comment by JojOatXGME** [comment]
Mhh, not sure if I understand you correctly because *“the expression above”* does not contain `/.`. In my tests, Nix 2.11.1 seems to parse `a.${foo}/b.${bar}` as the following.

    (a.${foo})(/b.${bar})

i.e. `a.${foo}` gets called as a function with `/b.${bar}` as a path which becomes the argument.

**Comment by jansorg** [comment]
Sorry, I meant `/b.`, not `/.`.
I don't know if Nix or the documentation is right. Is there perhaps a more official source or developer who could answer this?

**Comment by JojOatXGME** [comment]
I think the plugin should rather match the actual behavior of Nix than the documentation. I think even if the documented behavior would be considered more correct, it wouldn't provide much value if the plugin parses the expression correctly, as long as Nix doesn't.

> Is there perhaps a more official source or developer who could answer this?

Not sure. Maybe we should create a bug ticket for either Nix or the documentation. @Mic92, do you have an opinion about that?
