### ISSUE TITLE
Set “Trader” or “Non-Trader” State in JetBrains Account

### ISSUE THREAD

**Issue by JojOatXGME** [NixOS/nix-idea#71]
Hi @pSub, I think *nix-idea* is currently hosted on your account of JetBrains Marketplace, right? I got an email that all profiles have to specify whether they are a *“trader”* or a *“non-trader”*. If this option is not specified, we will not be able to publish any updates as of February 1, 2024.

> Hello,
>
> For compliance reasons, as of February 1, 2024, plugin updates will only be accepted if the plugin vendor has declared whether they can or cannot be considered a trader pursuant to the [Omnibus Directive 2019/2161](https://eur-lex.europa.eu/eli/dir/2019/2161/oj). Further details about the requirements can be found [here](https://plugins.jetbrains.com/docs/marketplace/trader-status.html).
>
> **Please check your [vendor profile](https://plugins.jetbrains.com/author/me) and update your vendor status as appropriate.**
>
> Thank you for your cooperation,
>
> **The JetBrains Marketplace team**
> The Drive to Develop

The rule seems to be required due to some legal changes in the EU. I am not quite sure how to understand the documentation. If we specify *“non-trader”*, it seems like JetBrains will somehow inform users, that *consumer protection laws* may not apply to the plugin. I guess specifying *non-trader* is the safer option, but not sure if we can just decide that on our own. Do you have any idea?

**Comment by pSub** [comment]
Hi @JojOatXGME, thank you for making me aware of this issue. I'll look into it today.

**Comment by pSub** [comment]
First of all, IANAL. From the explanation on the linked JetBrains site, I assume we are a _non-trader_. Especially the following example seems to confirm this:

> If you are a natural person (software developer) working for a company, but you develop plugins in your free time as a hobby and offer them for free and provide means for users to support your development on a voluntary basis (voluntary financial contribution), you may be qualified as a non-trader.

Currently, @edwtjo and me are listed as _developers_ on the plugin page. To select the vendor status we have to decide who is the vendor. That can be either @edwtjo, me or an (yet to be created) NixOS organization on the JetBrains Marketplace.

A NixOS organization as the vendor would be favorable in my opinion. It would make it easy for users to recognize the plugin as an _official_ plugin, rather than something developed by a random dude. However, I haven't created an organization on the JetBrains Marketplace before and don't know if there are any downsides or hurdles.

I'll call a lawyer later today to discuss the legal side of things. I have some "free lawyer time" from my legal cost insurance, so it is basically free for me. Lets see.

**Comment by pSub** [comment]
The requirements for a verified organization:

> For free plugin vendors – You must have a registered business entity, verify that you are authorized to do business under that name by providing supporting documentation (e.g., incorporation documentation, business or tax registration, or commercial register entries), and have at least one plugin on JetBrains Marketplace. Your contact information must include an active email address under a domain associated with your registered business entity.

https://plugins.jetbrains.com/docs/marketplace/verified-vendor-badge.html

**Comment by pSub** [comment]
I couldn't reach a lawyer familiar with this topic today. Maybe tomorrow. :crossed_fingers:

**Comment by JojOatXGME** [comment]
Regarding February 1, 2024. It is probably not a disaster if we don't set the flag in time. I guess as soon as we set the flag, the ability to publish updates would be restored. Anyway, I was quite surprised to get this notification only 1,5 weeks before the “deadline”...

> From the explanation on the linked JetBrains site, I assume we are a non-trader. Especially the following example seems to confirm this:

Yes, this would probably apply to us personally. The example fits quite well. However, I really don't understand what they mean with the following: “Plugin distribution outside of your trade, business, craft, or profession.” I mean, isn't software development my profession? 🤷‍♂️ I am also wondering if it would make a difference when we create a vendor representing the NixOS Foundation.

> To select the vendor status we have to decide who is the vendor. That can be either @edwtjo, me or an (yet to be created) NixOS organization

I guess we could technically also add me into the list, although I do not yet have access.

> A NixOS organization as the vendor would be favorable in my opinion.

Yes, feels like the way to go.

> The requirements for a verified organization:

Not sure if someone in the NixOS Foundation could provide such documents for the verification. Anyway, sounds like we only need this to **verify** a vendor. We could still create a vendor for Nix without verifying it.

https://plugins.jetbrains.com/docs/marketplace/organizations.html

Note that the `plugin.xml` currently declares `NixOS` as the vendor. We could therefore also use it as the vendor ID. However, the documentation warns that the ID should be chosen carefully, because it cannot be changed. Another option I would have in mind is `org.nixos`. Not sure if there are any conventions. At the end, it is probably not actually that important.

**Comment by JojOatXGME** [comment]
@pSub Do you have any new information? Otherwise, I would tend to create an organization and set it to “non-trader”.

**Comment by JojOatXGME** [comment]
@pSub I created an organization at https://plugins.jetbrains.com/organizations/NixOS/ as non-trader. (I think 2024.1 might be somewhat close, would be good to have this sorted out by then.)

On the page of the plugin, there should be a button to transfer the plugin. [Here are more information about the transfer](https://plugins.jetbrains.com/docs/marketplace/organizations.html#associating-plugin-with-organization). I am wondering if we should contact someone from the NixOS Foundation. I feel like it might be somewhat problematic to use “NixOS” without official consent from the “NixOS Foundation”. I provided my own email address for now. Do you know a good contact for that, or should I just email the public address?

PS: Looks there is also some more official guidance from the EU about who classifies as a trader at section 1.1 of https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A52021XC1229%2804%29&qid=1674657310759. Anyway, it is still not obvious, but I assume/hope that non-trader should be fine.

**Comment by JojOatXGME** [comment]
@pSub I just tried to publish a new version. Now, we know that the publish-job is actually failing due to this issue.

https://github.com/NixOS/nix-idea/actions/runs/8474515554/job/23221036029#step:7:361

**Comment by JojOatXGME** [comment]
The plugin now (since a few weeks already) belongs to the [NixOS organization I created](https://plugins.jetbrains.com/organizations/NixOS), and we have chosen non-trader. I will close the ticket.
