### ISSUE TITLE
Support for IntelliJ 2024.1

### ISSUE THREAD

**Issue by nekowinston** [NixOS/nix-idea#77]
Again marked as incompatible as of the most recent update: https://www.jetbrains.com/idea/whatsnew/2024-1/

**Comment by JojOatXGME** [comment]
Thanks for your reminder. I am aware of the issue, but unfortunately I have some problems to publish the latest release to the JetBrains Marketplace. Alternatively, you can download the latest release at https://github.com/NixOS/nix-idea/releases/download/v0.4.0.12/NixIDEA-0.4.0.12.zip for now.

**Comment by JojOatXGME** [comment]
Release got published to the Marketplace today.
