### ISSUE TITLE
Parsing issue with strings

### ISSUE THREAD

**Issue by hectorj** [NixOS/nix-idea#8]
Here is a screenshot of https://github.com/NixOS/nixpkgs/blob/ffb4797dd303589d48bae466ec4b735438f2244e/nixos/modules/services/networking/haproxy.nix open in Goglang with NixIdea v0.2.0.1:

![image](https://user-images.githubusercontent.com/2427959/27986080-ca10e72e-63f9-11e7-95cd-9e6c625a9b4a.png)

The file is valid, but it seems the plugin fails to detect the end of the string, or something like this? That's what the coloration make me think, but I'm not really sure.

The error it shows is a false positive, that's all I'm sure of.

Sorry I'm not very familiar with Java nor IntelliJ plugins so I haven't tried digging into the plugin's code yet to see if I could make a PR.

I hope this report helps.

**Comment by pSub** [comment]
I am aware of this issue. I hope I have time to prepare a PR soon.

**Comment by JojOatXGME** [comment]
I'm currently rewriting the parser and I just checked your example. Your example seems to work with the new implementation. I will close the ticket when I have finished my work and integrated my changes.
